edit the file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,19 +5,28 @@ on:
     branches:
       - master
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+# check Validate docker-compose.yml
 
-      - name: Build Docker
-        run: docker compose up -d --build
+validate:
+   name: Validate compose file
+   runs-on: ubuntu-latest
+   steps:
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - name: Check running containers
-        run: docker ps
-
-      - name: Shutdown
-        run: docker compose down
+      - name: Validate check
+        run: |
+           docker compose config --quiet
+           echo " docker-compose.yml is valid"
+      
+      - name: check all six services exist
+        run: 
+          for svc in zookeeper kafka kafka-ui elasticsearch scylladb redis; do
+            if docker compse config --services | grep -q "^${svc}&";then
+                echo " $svc is found"
+            else:
+                echo " $svc is not found"
+                exit 1
+            fi
+           done
